### ISSUE TITLE
Multi Select Option in Filters

### ISSUE THREAD

**Issue by MuhammadAmmad** [openshopio/openshop.io-ios#2]
@Skornos Hi, is there any way to apply multi select in filters?

**Comment by Skornos** [comment]
Hi Muhammad,

this feature is definitely implemented in the iOS project. Take a look at `BFSelectionViewController.h` and `multiSelection` property. You can see the example usage inside `BFFilterViewController` where we are setting the property currently to `false`. It is currently disabled because the feature is on TODO list for our server but if you use custom backend solution than it's no problem to enable it.

**Comment by MuhammadAmmad** [comment]
@Skornos Thanks a lot. You have done a great job

**Comment by MuhammadAmmad** [comment]
Hi, @Skornos I added multi selelct filters successfully. It is also selecting multiple filters nicely. But it is adding only first selected value of filter in params. Can you please guide me in which file I can get this code?Thanks.

**Comment by Skornos** [comment]
Hi @MuhammadAmmad our backend currently processes only one value in the filter. Multiple values are on TODO list.

**Comment by MuhammadAmmad** [comment]
@Skornos  I figured it out. Just have to append multi selected items with url. Thanks

**Comment by Skornos** [comment]
@MuhammadAmmad great. Hope you are satisfied with OpenShop.io codebase
